var english={
    "version": "1.4",
    "date": "2016-10-20",
    "name":{
    	"name":"zh"
    	},
	"_front": {
		"Cancel": "取消",
		"Confirm": "确认",
		"About_Us": "关于我们",
		"Account": "我的账户",
		"UP": "UP",
		"Libiray": "资料库",
		"Help": "帮助",
		"My_Account": "我的账户",
		"Setting": "设置",
		"Share": "分享",
		"Skin": "皮肤",
		"Language": "语言",
		"Current_Language": "当前语言",
		"Printer": "打印机",
		"No_UP_printers_found": "打印机未连接",
		"Failed_to_connect": "连接失败",
		"Connecting": "连接中…",
		"Printer_Name_Cannot_Be_Empty": "打印机名称不能为空",
		"Failed_to_locate_WiFi": "wifi查找失败",
		"Set_Success": "设置成功",
		"Please_Enter_Password": "请输入密码",
		"Upgrade": "软件升级",
		"Current": "当前版本",
		"Your_System_is_UPtodate": "当前版本已是最新",
		"Remind_me_of_the_new_version": "有版本更新时请提醒我",
		"Update": "升级",
		"Privacy_Policy": "隐私声明",
		"privacy": "请查看 UPStudio 的隐私声明以了解有关如何使用发送到 UPStudio 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
		"Details": "查看详情",
		"Skin_Color": "界面颜色",
		"Model_Color": "模型颜色",
		"Current_Color": "当前颜色",
		"Basic": "基础色",
		"Login": "登录",
		"Username_or_Email": "用户名/邮箱",
		"Sign_In": "登录",
		"Sign_Up": "注册",
		"Remember_Me": "记住密码",
		"Forgot_Password": "忘记密码？",
		"Login_Failed": "登录失败",
		"User_Account_has_not_been_Activated": "账户未激活",
		"User_does_not_Existed": "账户不存在",
		"Password_is_Incorrect": "密码错误",
		"Please_enter_your_username_and_password": "请输入用户名和密码",
		"Please_enter_user_name": "请输入用户名",
		"Please_enter_your_password": "请输入密码",
		"Network_Problems_and_Please_Try_Later": "网络出问题了，请稍后再试",
		"Login_Timeout": "登录超时",
		"Printer_Management": "打印机管理",
		"My_Printers": "我的打印机",
		"Serial_Number": "设备sn号",
		"Activation_Status": "激活状态",
		"Binding_Status": "绑定状态",
		"Activate": "激活",
		"Activated": "已激活",
		"Bind": "绑定",
		"Unbind": "解除绑定",
		"Success": "成功",
		"Unbind_Successfully": "解绑成功",
		"Failed_to_Unbind": "解绑失败",
		"Binding_Successfully": "绑定成功",
		"Activation_Succeeded": "激活成功",
		"Sign_out": "退出",
		"Username": "用户名（3-20个字符，子母开头）",
		"Emailenter": "邮箱（请输入您的邮箱）",
		"Password": "密码（6-32个字符）",
		"Confirm_Password": "确认密码（再次输入密码）",
		"Registration_means_you_agree_with": "注册表示您同意",
		"Tiertime_End_User_Agreement": "《太尔时代用户协议》",
		"Invalid_Username": "用户名输入不合法",
		"Invalid_Email_Address": "邮箱输入不合法",
		"Invalid_Password": "密码输入不合法",
		"Passwords_Do_Not_Match": "两次密码输入不一致",
		"Username_has_been_used": "用户名已存在",
		"Email_account_has_been_used": "邮箱已存在",
		"Registration_Successful": "注册成功",
		"Congratulations": "恭喜",
		"success_text": "注册成功，激活码已发送到您的邮箱，请点击激活",
		"Email": "邮箱",
		"Error": "错误",
		"Email_or_Username_Error": "用户名或邮箱错误",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "重置密码邮件发送成功",
		"Failed_to_Reset_Password": "重置密码失败",
		"Home": "主页",
		"Import_Model_or_Image": "添加模型或图片",
		"Print": "打印",
		"Initialize_Printer": "初始化打印机？",
		"Calibrate": "校准",
		"Maintenance": "维护",
		"Model_Properties": "模型属性",
		"Basic_Information": "基本信息",
		"File_Path": "文件路径:",
		"Size": "模型尺寸(mm): ",
		"MinSize": "最小位置(mm): ",
		"MaxSize": "最大位置(mm): ",
		"Vertex_Number": "顶点数目:",
		"Facet_Number": "面片数目:",
		"Volume": "体积(mm³): ",
		"Surface_Area": "表面积(mm²):",
		"Move": "移动",
		"Scale": "缩放",
		"More": "类别",
		"View": "视图",
		"Undo": "回退",
		"Auto_Place": "自动摆放",
		"Rotate": "旋转",
		"Mirror": "镜像",
		"Save_Model": "保存模型",
		"Reset_to_Default": "重置",
		"Fix_Errors": "修复",
		"Merge": "合并",
		"Delete": "删除",
		"Top_View": "顶视图",
		"Bottom_View": "底视图",
		"Back_View": "后视图",
		"Free_View": "自由视图",
		"Right_View": "右视图",
		"Front_View": "前视图",
		"Left_View": "左视图",
		"Wait_a_moment": "稍等片刻…",
		"Range_is_from": "只能输入",
		"No_Axis_Chosen": "没有选择轴向",
		"Add": "添加",
		"Add_Picture": "添加图片",
		"Add_Mode": "添加模型",
		"Saving": "保存中",
		"Printer_Setting": "打印设置",
		"Normal": "默认",
		"Layer_Thickness": "层片厚度",
		"Infill": "填充方式",
		"Shell": "",
		"Surface": "",
		"Solid": "",
		"Loose": "",
		"Hollow": "",
		"Big_Hole": "",
		"Quality": "质量",
		"Fine": "较好",
		"Fast": "较快",
		"Turbo": "几块",
		"Option": "选项",
		"Preference": "高级",
		"Dormancy": "休眠",
		"Preview": "打印预览",
		"Select_Saved_Slot": "选择保存的槽位",
		"Reprint": "重复打印",
		"Slot": "槽位",
		"Number": "序号",
		"Model_Name": "模型名称",
		"Time": "时间",
		"Date": "日期",
		"Choose": "选择",
		"Part": "密闭",
		"Angle": "角度",
		"Support": "支撑",
		"Dense": "支撑层数",
		"Area": "支撑面积",
		"Space": "支撑间隔",
		"No_Raft": "无底座",
		"No_Support": "无支撑",
		"Stable_Support": "稳固支撑",
		"Others": "其他",
		"Unsolid_Model": "非实体模型",
		"Thin_Wall": "薄壁",
		"Preheat": "预热",
		"Default": "设置模型",
		"Calibration": "平台校准",
		"Platform_Calibration": "平台点位校准",
		"Manual": "手动校准",
		"Auto_Level": "自动补偿",
		"Reset": "重置",
		"Nozzle_Height": "喷嘴高度",
		"Set": "设置",
		"Nozzle_Detect": "自动对高",
		"Demo_Op": "演示操作",
		"Demo_Op_Over": "演示结束",
		"Set_nozzle_height_is": "设置喷嘴高度为:",
		"Compensation": "补偿",
		"Set_Nozzle_Height_as": "保存喷嘴高度为",
		"Platform_Auto_Calibration_in_Progress": "平台自动调整中，请稍后…",
		"Nozzle_Auto_Calibration_in_Progress": "喷嘴自动调整中，请稍候…",
		"Please_Choose_Plate_Type": "请选择底板类型",
		"Perforated": "多孔板",
		"Flex": "Flex板",
		"Extrude": "挤出",
		"Withdraw": "撤回",
		"Stop": "停止",
		"Material": "材料",
		"Weight": "重量",
		"Customized": "自定义",
		"Customized_Material": "自定义材料",
		"Name": "名称",
		"Nozzle": "喷嘴(℃)",
		"Platform": "底板(℃)",
		"Process": "操作",
		"Please_sign_in_your_account": "请登录您的账户",
		"Material_Name_Duplicated": "错误：材料名称重复",
		"Only_7_Materials_Allowed": "自定义材料最多7个",
		"Fields_can_not_be_Empty": "填写不完整",
		"Please_Enter_Numbers": "请输入数字",
		"Only_Numbers_and_Characters_Allowed": "只允许数字或子母",
		"Stop_Printing": "停止打印",
		"Pause": "暂停打印",
		"Resume": "恢复打印",
		"Stop_Preview": "停止预览",
		"Confirm_to_Stop": "确认停止？",
		"Stop_the_Current_Print_Job": "确认停止打印？",
		"Time_Left": "剩余",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "计算中",
		"Sending": "传输中"
	},
	"print": {
		"PrinterStatus-1": "打印机未连接",
		"PrinterStatus0": "未初始化",
		"PrinterStatus1": "打印机准备就绪",
		"PrinterStatus2": "打印中",
		"PrinterStatus3": "暂停打印",
		"PrinterStatus4": "喷嘴错误",
		"PrinterStatus5": "运动系统错误",
		"PrinterStatus6": "打印完成",
		"PrinterStatus7": "打印被停止",
		"PrinterStatus8": "喷嘴温度过高",
		"PrinterStatus9": "喷嘴温度过低",
		"PrinterStatus10": "平台温度过高",
		"PrinterStatus11": "tt_reverse_1",
		"PrinterStatus12": "tt_reverse_2",
		"PrinterStatus13": "tt_reverse_3",
		"PrinterStatus14": "tt_reverse_4",
		"PrinterStatus15": "系统上电",
		"PrinterStatus16": "SD卡错误",
		"PrinterStatus17": "SD卡写入错误",
		"PrinterStatus18": "SD卡读取错误",
		"PrinterStatus19": "保存打印数据至SD卡",
		"PrinterStatus20": "移动指令错误",
		"PrinterStatus21": "版权限制",
		"PrinterStatus22": "打印次数限制",
		"PrinterStatus23": "通讯错误",
		"ERROR": "发生错误",
		"ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
		"ERROR: Incorrect material": "错误：打印机材料设置错误",
		"ERROR: Printer status error": "错误：打印机状态错误",
		"ERROR: Slicing error": "错误：分层错误",
		"ERROR: Printer connection error": "错误：打印机连接错误",
		"ERROR: Data transfer failure": "错误：传输打印数据失败",
		"ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
		"ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
		"ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
		"ERROR: Nozzleheight set error</br>Correct range:": "错误：喷头高度设置错误</br>正确范围：",
		"Repeat last print?": "确定重复打印吗？",
		"ERROR: Other error ": "错误：其他错误 ",
		"Language test": "当前语言为中文",
		"Are you sure to stop the print job?": "确定停止打印吗？",
		"Found a new version": "发现新版本",
		",download it immediately?": "，是否立即更新？",
		"[YES]: Update immediately": "[是]：立即更新",
		"[NO]: Remind me later": "[否]：下次通知我",
		"[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
		"Note: Download will be running in the background, after the completion of the notice": "注意：下载将在后台运行。 完成后，您将收到通知。",
		"Update": "升级",
		"No new version": "无新版本",
		"ERROR: The model is opening, please try again later": "错误：正在读取模型，请稍后再试",
		"ERROR: Temperature is too high": "错误：温度过高",
		"ERROR: Sensor not connected": "传感器未连接",
		"ERROR: Calibration failure": "错误：校准失败",
		"ERROR: Printer is busy": "错误：系统正忙",
		"Success，Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
		"ERROR: Printer error": "错误：打印机错误",
		"Print: ": "打印时间：",
		"Material: ": "耗费材料：",
		"g": "克",
		"H": "小时",
		"M": "分钟",
		"S": "秒",
		"ERROR: Templete directory get error": "错误：临时文件路径获取失败",
		"ERROR: Create dir error": "错误：创建目录失败",
		"ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
		"ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
		"ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
		"ERROR:Model does not exist": "错误：模型不存在",
		"Activation": "激活",
		"Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
		"Activation state error, need to return to the factory": "激活状态错误，请返厂",
		"OK": "确定",
		"CANCEL": "取消",
		"YES": "是",
		"NO": "否",
		"ABORT": "退出",
		"RETRY": "重试",
		"IGNORE": "忽略",
		"Save successful": "保存成功",
		"Save failed": "保存失败",
		"Downloading, please wait": "正在下载，请稍等片刻",
		",upgrade now?": ",立刻升级？",
		"Level data save error": "调平数据保存错误",
		"ERROR: Printer no response": "错误：打印机无响应",
		"ERROR: Printer password error": "错误：密码错误",
		"ERROR: Printer connected by other clients": "错误：打印机被占用",
		"ERROR: Printer none certification": "错误：打印机未认证",
		"Connection OK": "连接成功",
		"Connection Error": "连接失败",
		"Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
		"Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
		"No Model Selected": "没有选中的模型",
		"warning!": "警告!",
		"    Delete Selected Model?": "    是否删除选中模型?",
		"    Delete All Models?": "    是否删除全部模型?",
		"Please close the front door": "请关闭前门",
		"Model is too large! Can not Load": "模型过大！不能导入！",
		"Loading Failed": "模型载入失败！",
		"Print job stopped at ": "打印任务停在第",
		"th layer, resume the print?": "层，是否恢复打印?",
		"ERROR:  Can't resume the broken print job": "错误：无法恢复已停止的打印作业。",
		"ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL 版本过低，请更新显卡驱动",
		"ERROR: Printer SN Error": "错误：打印机序列号有问题",
		"ERROR: Unknow error": "错误：未知错误",
		"ERROR: Invalide activekey": "错误：激活码错误",
		"ERROR: No factory actived": "错误：不是工厂激活状态",
		"ERROR: Active error,wrong key": "错误：激活失败，错误的激活码",
		"ERROR: The server returns the activation code to parse the JSON failed": "错误：服务器返回信息解析JSON失败",
		"ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
		"ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
		"ERROR: The current state of activation is not factory activation": "错误：当前的激活状态不是工厂激活",
		"ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
		"ERROR: Model out of print bound": "错误：模型超出打印范围",
		"ERROR: Calibration Failure": "错误：校准失败",
		"ERROR: Server connection failed": "错误：服务器连接失败",
		"ERROR: Verification Failed,Please download activation package": "错误: 校验失败，请下载校验文件",
		"[YES] Perf Board\n[NO] Flex Board": "",
		"Please Select The Type Of Plat": "请选择底板类型",
		"ERROR: Temperature is low": "错误：喷头温度低",
		"Do you want to keep current model?": "是否保留当前模型?"
	},
	"graphic": {
		"Filepath: ": "文件路径: ",
		"Size(mm): ": "模型尺寸: ",
		"Min-Size(mm): ": "最小位置: ",
		"Max-Size(mm): ": "最大位置: ",
		"Vertex Number: ": "顶点数目: ",
		"Facet Number: ": "面片数目: ",
		"Volume: ": "体积: ",
		"Copying...": "模型复制中，请等待...",
		"Saveing...": "模型保存中，请等待...",
		"has scaled from inch unit to mm unit!": "模型过小，已放大25.4倍（inch）！",
		"Property": "属性",
		"Merge": "合并模型",
		"Copy": "复制",
		"1 model": "1个模型",
		"2 model": "2个模型",
		"5 model": "5个模型",
		"Delete": "删除",
		"Delete All": "全部删除",
		"Select All": "全部选择",
		"UnSelect All": "全不选择",
		"Initialize View": "复原视图",
		"Rotate By Models Center": "绕模型中心旋转",
		"Exit": "退出"
	},
	"image_front": {
		"_Model_Height": "模型高度",
		"_Base_Height": "基底高度",
		"_Style": "风格",
		"_Model_Size": "模型大小",
		"_Unit": "单位(mm)",
		"_Pen_Size": "画笔大小",
		"_Pen_Color": "画笔颜色",
		"_Pen_Type": "画笔种类",
		"_Erase_Size": "橡皮擦大小",
		"_Font": "字体",
		"_Font_Size": "文字大小",
		"_Font_Color": "文字颜色",
		"_Constrain": "等比例",
		"_Tools": "工具",
		"_Setting": "设置",
		"_Previous": "上一步",
		"_Apply": "应用",
		"_Toggle_color": "黑白转换"
	},
     "image": { }
}
