var english={
    "name":{
    	"version": "1.6",
	"date": "2017-03-7",
       	"name":"zh"
    },
	"_front": {
		"Cancel": "取消",
		"Confirm": "确认",
		"About_Us": "关于我们",
		"Account": "我的账户",
		"UP": "UP",
		"Libiray": "模型库",
		"Help": "帮助",
		"My_Account": "我的账户",
		"Setting": "设置",
		"Skin": "皮肤",
		"Language": "语言",
		"Current_Language": "当前语言",
		"Printer": "打印机",
		"No_UP_printers_found": "打印机未连接",
		"Printer_Name_Cannot_Be_Empty": "打印机名称不能为空",
		"Failed_to_locate_WiFi": "wifi查找失败",
		"Set_Success": "设置成功",
		"Please_Enter_Password": "请输入密码",
		"Upgrade": "软件升级",
		"Current": "当前版本",
		"Your_System_is_UPtodate": "当前版本已是最新",
		"Remind_me_of_the_new_version": "有版本更新时请提醒我",
		"Update": "升级",
		"Privacy_Policy": "隐私声明",
		"privacy": "请查看 Tiertime 的隐私声明以了解有关如何使用发送到 Tiertime 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
		"Details": "查看详情",
		"Skin_Color": "界面颜色",
		"Model_Color": "模型颜色",
		"Basic": "基础色",
		"Login": "登录",
		"Username_or_Email": "用户名/邮箱",
		"Sign_In": "登录",
		"Sign_Up": "注册",
		"Forgot_Password": "忘记密码？",
		"Login_Failed": "登录失败",
		"User_Account_has_not_been_Activated": "账户未激活",
		"User_does_not_Existed": "账户不存在",
		"Password_is_Incorrect": "密码错误",
		"Please_enter_your_username_and_password": "请输入用户名和密码",
		"Please_enter_user_name": "请输入用户名",
		"Please_enter_your_password": "请输入密码",
		"Network_Problems_and_Please_Try_Later": "网络出问题了，请稍后再试",
		"Login_Timeout": "登录超时",
		"Printer_Management": "打印机管理",
		"Serial_Number": "设备sn号",
		"Activation_Status": "激活状态",
		"Binding_Status": "绑定状态",
		"Activate": "激活",
		"Activated": "已激活",
		"Bind": "绑定",
		"Unbind": "解除绑定",
		"Success": "成功",
		"Unbind_Successfully": "解绑成功",
		"Failed_to_Unbind": "解绑失败",
		"Binding_Successfully": "绑定成功",
		"Activation_Succeeded": "激活成功",
		"Sign_out": "退出当前账户",
		"Username": "用户名（3-20个字符，字母开头）",
		"Emailenter": "邮箱（请输入您的邮箱）",
		"Password": "密码（6-32个字符）",
		"Confirm_Password": "确认密码（再次输入密码）",
		"Registration_means_you_agree_with": "注册表示您同意",
		"Tiertime_End_User_Agreement": "《太尔时代用户协议》",
		"Invalid_Username": "用户名输入不合法",
		"Invalid_Email_Address": "邮箱输入不合法",
		"Invalid_Password": "密码输入不合法",
		"Passwords_Do_Not_Match": "两次密码输入不一致",	
		"Registration_Successful": "注册成功",
		"Congratulations": "恭喜",
		"success_text": "注册成功，激活码已发送到您的邮箱，请点击激活",
		"Email": "邮箱",
		"Error": "错误",
		"Email_or_Username_Error": "用户名或邮箱错误",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "重置密码邮件发送成功",
		"Failed_to_Reset_Password": "重置密码失败",
		"Home": "主页",
		"Import_Model_or_Image": "添加模型或图片",
		"Print": "打印",
		"Initialize_Printer": "初始化打印机",
		"Calibrate": "校准",
		"Maintenance": "维护",
		"Move": "移动",
		"Scale": "缩放",
		"More": "类别",
		"View": "视图",
		"Undo": "回退",
		"Auto_Place": "自动摆放",
		"Rotate": "旋转",
		"Mirror": "镜像",
		"Save_Model": "保存模型",
		"Reset_to_Default": "重置",
		"Fix_Errors": "修复",
		"Merge": "合并",
		"Delete": "删除",
		"Top_View": "顶视图",
		"Bottom_View": "底视图",
		"Back_View": "后视图",
		"Free_View": "自由视图",
		"Right_View": "右视图",
		"Front_View": "前视图",
		"Left_View": "左视图",
		"Wait_a_moment": "稍等片刻…",
		"Range_is_from": "只能输入",
		"No_Axis_Chosen": "没有选择轴向",
		"Add": "添加",
		"Add_Picture": "添加图片",
		"Add_Mode": "添加模型",
		"Saving": "保存中",
		"Printer_Setting": "打印设置",
		"Normal": "默认",
		"Layer_Thickness": "层片厚度",
		"Infill": "填充方式",
		"Quality": "质量",
		"Fine": "较好",
		"Fast": "较快",
		"Turbo": "极快",
		"Option": "选项",
		"Preference": "高级",
		"Dormancy": "休眠",
		"Preview": "打印预览",
		"Select_Saved_Slot": "选择保存的槽位",
		"Reprint": "重复打印",
		"Slot": "槽位",
		"Number": "序号",
		"Time": "时间",
		"Date": "日期",
		"Choose": "选择",
		"Part": "密闭",
		"Surface": "密闭层数",
		"Angle": "角度",
		"Support": "支撑",
		"Dense": "支撑层数",
		"Area": "支撑面积",
		"Space": "支撑间隔",
		"No_Raft": "无底座",
		"No_Support": "无支撑",
		"Stable_Support": "稳固支撑",
		"Others": "其他",
		"Unsolid_Model": "非实体模型",
		"Thin_Wall": "薄壁",
		"Preheat": "预热",
		"Default": "设置默认",
		"Calibration": "平台校准",
		"Platform_Calibration": "平台点位校准",
		"Manual": "手动校准",
		"Auto_Level": "自动补偿",
		"Reset": "重置",
		"Nozzle_Height": "喷嘴高度",
		"Set": "设置",
		"Nozzle_Detect": "自动对高",
		"Demo_Op": "演示操作",
		"Demo_Op_Over": "演示结束",
		"Set_nozzle_height_is": "设置喷嘴高度为:",
		"Compensation": "补偿",
		"Set_Nozzle_Height_as": "保存喷嘴高度为",
		"Extrude": "挤出",
		"Withdraw": "撤回",
		"Stop": "停止",
		"Material": "材料",
		"Weight": "重量",
		"Customized": "自定义",
		"Customized_Material": "自定义材料",
		"Name": "名称",
		"Nozzle": "喷嘴(℃)",
		"Platform": "底板(℃)",
		"Process": "操作",
		"Please_sign_in_your_account": "请登录您的账户",
		"Material_Name_Duplicated": "材料名称重复",
		"Only_7_Materials_Allowed": "自定义材料最多7个",
		"Fields_can_not_be_Empty": "填写不完整",
		"Stop_Printing": "停止打印",
		"Pause": "暂停打印",
		"Resume": "恢复打印",
		"Stop_Preview": "停止预览",
		"Stop_the_Current_Print_Job": "确认停止？",
		"Time_Left": "剩余",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "计算中 ",
		"Sending": "传输中 ",
		"offical_initerface": "官方材料",
		"series_number": "序列号",
		"serial_password": "密码",
		"please_series_number": "请输入序列号",
		"My_model": "我的模型",
		"Public_model":"精品",
		"Self_model":"私有",
		"Save_model": "收藏",
		"Share_model": "发布",
		"Buy_model": "购买",
		"My_print": "我的打印机",
		"Find_all_print": "查看所有打印机",
		"User_number": "用户积分",
		"Change_password": "修改密码",
		"upload_model": "上传模型",
		"upload": "上传",
		"upload_list": "上传列表",
		"readmessage": "正在准备数据传输 ···",
		"All": "全部",
		"Free": "免费",
		"Pay": "付费",
		"Model_parameter": "模型参数",
		"Model_Size": "模型大小",
		"Model_price": "模型积分",
		"Model_filder": "模型文件",
		"Print_count": "打印次数",
		"Model_buy": "购买模型",
		"Model_save": "收藏",
		"Model_al_save": "已收藏",
		"Model_download": "下载模型",
		"Model_deleat": "删除模型",
		"Model_desript": "模型描述",
		"Model_name": "模型名称",
		"Download_on": "下载",
		"Model_share": "分享",
		"Cancel_upload": "取消发布",
		"All_download": "全部下载",
		"All_open": "全部打开",
		"Model_attr": "模型属性",
		"Model_information": "模型信息",
		"Filepath": "文件路径: ",
		"Size": "模型尺寸: ",
		"Min_Size": "最小位置: ",
		"Max_Size": "最大位置: ",
		"Vertex_Number": "顶点数目: ",
		"Facet_Number": "面片数目: ",
		"Volume": "体积:",
		"Surface_Area": "表面积:",
		"Inch": "英寸",
		"Mm": "毫米",
		"Alerady_buy": "已购买",
		"Manage" : "管理",
		"Model_unit": "单位:",
		"Auto_height_end": "自动对高结束",
		"Flex_plat": "麦拉片",
		"Ward_plat": "蜂窝板",
		"Model_upload": "发布",
		"Model_points": "积分",
		"Unlimited": "无限制",
		"Error_prompt": "发生错误",
		"Connection_failed": "连接失败",
		"User_and_password": "用户名和密码不能为空",
		"User_and_password_already": "用户名或邮箱已存在",
		"Calibration_failure_temp_hot": "校准失败，喷头温度过高",
		"Member_login_in_auto": "自动登录",
		"Model_list_nav": "导航",
		"Model_share_cancle":  "已取消",
		"Keep_on_download": "继续下载",
		"Model_buy": "购买",
		"Model_preparing":"正在准备数据，不能关闭",
		"LatestVersion": "最新版本 V.",
		"Failed_to_bind": "绑定失败",
		"Custom_material_information_empty":"自定义材料信息不能为空",
		"Clear_cache": "清理缓存",
		"Clear_download_model": "清除已下载模型",
		"Clear_cache_file": "清除缓存文件",
		"Compensation_height": "补偿高度",
		"Current_nozzle_height_print": "当前喷嘴高度",
		"Model_insert": "模型插入",
		"Advanced_print": "高级打印",
		"Pause_position": "暂停位置",
		"Pause_height": "高度",
		"Print_cao": "打印槽位",
		"Pause_print_exame": "输入需要暂停的高度（毫米）例如：7.6",
		"Model_audit": "审核中",
		"Model_re_publish": "重新发布",
		"Cancel_clear_up": "取消清理",
		"Clear_finish": "清理完成",
		"Nozzle_diameter": "喷嘴直径",
		"Infill_wrap": "Shell",
		"Infill_surface": "Surface",
		"Infill_style1": "13%",
		"Infill_style2": "15%",
		"Infill_style3": "20%",
		"Infill_style4": "65%",
		"Infill_style5": "80%",
		"Infill_style6": "99%",
		"Manual_activation": "手动激活",
		"Manual_file": "请载入activeCode.act文件以激活打印机",
		"Copy_message": "复制信息到剪贴板",
		"Manual_fail": "从服务器返回激活码失败",
		"Manual_download": "载入",
		"Manual_connecting": "正在激活,请等待...",
		"Platform_leval": "水平校准",
		"Platform_vertival": "垂直校准",
		"Model_default_color": "默认色",
		"Model_color_design": "编辑",
		"Manual_have_code": "如果已经有激活码,可以尝试",
		"Manual_copy_success": "复制成功",
		"Infinite_print_price": "无限打印积分",
		"Once_print_price": "单次打印积分",
		"Model_print_price": "模型打印价格",
		"Print_infinite": "无限次",
		"Model_buy_times": "购买次数",
		"Manual_email": "如果您没有这个文件,您可以登录",
		"Model_publish_limited": "无限次的价格不得低于单次模型的价格",
		"Manual_pass_information": "复制以下信息:",
		"Manual_get_code":"获取激活文件ActiveCode.act,手动激活打印机",
		"Colud_Print":"正在使用云端参数打印",
		"Manual_active_login_font": "您可以登录",
		"Manual_get_code_select": "获取activeCode.act",
		"Manual_send_email": "发送以下信息到zhangyh@tiertime.net获取:",
		"Manual_select_hide": "收起",
		"Check_upload_ups":"错误：不能上传受保护的模型",
		"Model_Skin_Color":"默认模型颜色",
		"Easy_peel":"易于剥离",

		"Model_count_number": "打印次数不能小于1",
		"Local_model": "本地",
		"Load_check": "加载选中"
	},
	"print": {
		"PrinterStatus-1":"打印机未连接",
		"PrinterStatus0": "未初始化",
		"PrinterStatus1": "打印机准备就绪",
		"PrinterStatus2": "打印中",
		"PrinterStatus3": "暂停打印",
		"PrinterStatus4": "喷嘴错误",
		"PrinterStatus5": "运动系统错误",
		"PrinterStatus6": "打印完成",
		"PrinterStatus7": "打印被停止",
		"PrinterStatus8": "喷嘴温度过高",
		"PrinterStatus9": "喷嘴温度过低",
		"PrinterStatus10": "平台温度过高",
		"PrinterStatus11": "tt_reverse_1",
		"PrinterStatus12": "tt_reverse_2",
		"PrinterStatus13": "tt_reverse_3",
		"PrinterStatus14": "tt_reverse_4",
		"PrinterStatus15": "系统上电",
		"PrinterStatus16": "SD卡错误",
		"PrinterStatus17": "SD卡写入错误",
		"PrinterStatus18": "SD卡读取错误",
		"PrinterStatus19": "保存打印数据至SD卡",
		"PrinterStatus20": "移动指令错误",
		"PrinterStatus21": "版权限制",
		"PrinterStatus22": "打印次数限制",
		"PrinterStatus23": "通讯错误",
		"ERROR": "发生错误",
		"ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
		"ERROR: Incorrect material": "错误：打印机材料设置错误",
		"ERROR: Printer status error": "错误：打印机状态错误",
		"ERROR: Printer connection error": "错误：打印机连接错误",
		"ERROR: Data transfer failure": "错误：传输打印数据失败",
		"ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
		"ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
		"ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
		"Correct range": "正确范围",
		"Repeat last print?": "确定重复打印吗？",
		"ERROR: Other error ": "错误：其他错误 ",
		"Language test": "当前语言为中文",
		"Are you sure to stop the print job?": "确定停止吗？",
		"Found a new version": "发现新版本",
		",download it immediately?": "，是否立即更新？",
		"[YES]: Update immediately": "[是]：立即更新",
		"[NO]: Remind me later": "[否]：下次通知我",
		"[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
		"Note: Download will be running in the background, after the completion of the notice": "注意：下载将在后台运行。 完成后，您将收到通知。",
		"Update": "升级",
		"No new version": "无新版本",
		"ERROR: Temperature is too high": "错误：温度过高",
		"ERROR: Sensor not connected": "传感器未连接",
		"ERROR: Calibration Failure": "错误：校准失败",
		"ERROR: Printer is busy": "错误：系统正忙",
		"Success，Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
		"ERROR: Printer error": "错误：打印机错误",
		"Print: ": "打印时间：",
		"Material: ": "耗费材料：",
		"g": "克",
		"H": "小时",
		"M": "分钟",
		"S": "秒",
		"ERROR: Templete directory get error": "错误：临时文件路径获取失败",
		"ERROR: Create dir error": "错误：创建目录失败",
		"ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
		"ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
		"ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
		"ERROR:Model does not exist": "错误：模型不存在",
		"Activation": "激活",
		"Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
		"Activation state error, need to return to the factory": "激活状态错误，请返厂",
		"OK": "确定",
		"CANCEL": "取消",
		"YES": "是",
		"NO": "否",
		"ABORT": "退出",
		"RETRY": "重试",
		"IGNORE": "忽略",
		"Save successful": "保存成功",
		"Save failed": "保存失败",
		"Downloading, please wait": "正在下载，请稍等片刻",
		",upgrade now?": ",立刻升级？",
		"Level data save error": "调平数据保存错误",
		"ERROR: Printer no response": "错误：打印机无响应",
		"ERROR: Printer password error": "错误：密码错误",
		"ERROR: Printer connected by other clients": "错误：打印机被占用",
		"ERROR: Printer none certification": "错误：打印机未认证",
		"Connection OK": "连接成功",
		"Connection Error": "连接失败",
		"Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
		"Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
		"No Model Selected": "没有选中的模型",
		"warning!": "警告!",
		"    Delete Selected Model?": "    是否删除选中模型?",
		"    Delete All Models?": "    是否删除全部模型?",
		"Please close the front door": "请关闭前门",
		"Model is too large! Can not Load": "模型过大！不能导入！",
		"Loading Failed": "模型载入失败！",
		"Print job stopped at ": "打印任务停在第",
		"th layer, resume the print?": "层，是否恢复打印?",
		"ERROR:  Can not resume the broken print job": "错误：无法恢复已停止的打印作业。",
		"ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL 版本过低，请更新显卡驱动",
		"ERROR: Printer SN Error": "错误：打印机序列号有问题",
		"ERROR: Unknow error": "错误：未知错误",
		"ERROR: Invalide activekey": "错误：激活码错误",
		"ERROR: No factory actived": "错误：不是工厂激活状态",
		"ERROR: Active error,wrong key": "错误：激活失败，错误的激活码",
		"ERROR: The server returns the activation code to parse the JSON failed": "错误：服务器返回信息解析JSON失败",
		"ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
		"ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
		"ERROR: The current state of activation is not factory activation": "错误：当前的激活状态不是工厂激活",
		"ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
		"ERROR: Model out of print bound": "错误：模型超出打印范围",
		"ERROR: Server connection failed": "错误：服务器连接失败",
		"ERROR: Verification Failed,Please download activation package": "错误: 校验失败，请下载校验文件",
		"Please Select The Type Of Plat": "请选择底板类型",
		"ERROR: Temperature is low": "错误：喷头温度低",
		"Do you want to keep current model?": "是否保留当前模型?",
		"ERROR: Image read failed": "错误：图片读取失败",
        "Multiple": "多个",
        "ERROR：Please select the model you need to upload": "错误：请选取需要上传的模型",
        "Initialize_Printer": "初始化打印机",
        "ERROR: Material modification failure": "错误：材料修改失败",
        "Price":"价格",
		"Point":"积分",
		"Sure to buy":"确定购买吗",
		"ERROR: Upload Error": "错误：上传错误",
        "ERROR: Network Disconnection": "错误：网络断开",
        "ERROR: Cancel publish failure":"错误：取消发布失败",
        "The printer does not support this feature":"打印机不支持该功能",
        "Print finished, please take out the model":"打印完成，请取出模型",
        "Cancel":"取消",
		"Not Prompt":"不再提醒",
		"No material detected, please replace it":"未检测到材料，请更换",
		"ERROR: Publish failure":"发布失败",
		"ERROR:Gcode failed to run":"Gcode运行失败",
		"Run File":"运行文件",
		"ERROR: Input Not Valid":"错误：输入无效",
		"Select active file":"选择激活文件",
		"ERROR: X1 Or X2 Input Error":"错误：X1或X2输入错误",
		"ERROR: Z Or H Input Error":"错误：Z或H输入错误",
		"ERROR: Save Error":"错误：保存失败",
		"ERROR: User Not Login":"错误：用户未登录",
		"ERROR: Model validation failure":"错误：模型验证失败",
		"Can Not Open File!":"无法打开文件！",
		"Can Not Verify File!":"无法验证文件！",
		"User Does Not Match!":"用户不匹配！",
		"ERROR: Clear SD card error":"错误：清理SD卡错误",
		"Clear SD card ok":"清理SD卡成功"

	},
	"graphic": {
		"Filepath: ": "文件路径: ",
		"Size: ": "模型尺寸: ",
		"Min-Size: ": "最小位置: ",
		"Max-Size: ": "最大位置: ",
		"Vertex Number: ": "顶点数目: ",
		"Facet Number: ": "面片数目: ",
		"Volume: ": "体积: ",
		"Copying...": "模型复制中，请等待...",
		"Saveing...": "模型保存中，请等待...",
		"has scaled from inch unit to mm unit!": "模型过小，已放大25.4倍！",
		"Property": "属性",
		"Merge": "合并模型",
		"Copy": "复制",
		"1 model": "1个模型",
		"2 model": "2个模型",
		"5 model": "5个模型",
		"Delete": "删除",
		"Delete All": "全部删除",
		"Select All": "全部选择",
		"UnSelect All": "全不选择",
		"Initialize View": "复原视图",
		"Rotate By Models Center": "绕模型中心旋转",
		"Exit": "退出",
		"app is not verified":"程序未校验",
		"The file is damaged": "文件已损坏",
		"current models contain protected model! can not do this operation!":"当前模型中包含受保护的模型！不能进行此操作！",
		"UnKnown ERROR!Please Contact TierTime!":"未知错误！请联系太尔时代"
	},
	"image_front": {
		"_Model_Height": "模型高度",
		"_Base_Height": "基底高度",
		"_Style": "风格",
		"_Model_Size": "模型大小",
		"_Unit": "单位(mm)",
		"_Pen_Size": "画笔大小",
		"_Pen_Color": "画笔颜色",
		"_Pen_Type": "画笔种类",
		"_Erase_Size": "橡皮擦大小",
		"_Font": "字体",
		"_Font_Size": "文字大小",
		"_Font_Color": "文字颜色",
		"_Constrain": "等比例",
		"_Tools": "工具",
		"_Setting": "设置",
		"_Previous": "上一步",
		"_Apply": "应用",
		"_Go_back": "返回",
		"_Pen": "画笔",
		"_Rubber": "橡皮",
		"_Text": "文字",
		"_Cut": "裁剪",
		"_Toggle_color": "黑白转换"
	},
	"IOS_Ipad_Iphone":{
		"Version":"1.0.1",
    "name": "简体中文",
    "Stop": "停止",
    "Extrude":"挤出",
    "WithDraw":"撤丝",
    "SN":"序列号",
    "ModelName":"模型名称",
    "Archive":"文档",
    "Infill":"填充",
    "Register_success":"注册成功",
    "Congratulation":"恭喜",
    "ActivationCode":"注册成功,激活码已发到您的邮箱,请点击激活",
    "systemError": "系统错误",
    "tt_systemunlink": "打印机未连接",
    "tt_systemerror": "未初始化",
    "tt_prepared": "打印机准备就绪",
    "tt_runing": "打印中",
    "tt_pause": "暂停打印",
    "tt_nozzleerror": "喷嘴错误",
    "tt_motionerror": "运动系统错误",
    "tt_finished": "打印完成",
    "tt_userstop": "打印被停止",
    "tt_temphigh": "喷嘴温度过高",
    "tt_templow": "喷嘴温度过低",
    "tt_workroomhigh": "平台温度过高",
    "tt_reverse_1": "tt_reverse_1",
    "tt_reverse_2": "tt_reverse_2",
    "tt_reverse_3": "tt_reverse_3",
    "tt_reverse_4": "tt_reverse_4",
    "tt_systempoweron": "系统上电",
    "tt_sdcarderror": "SD卡错误",
    "tt_sdwberror": "SD卡写入错误",
    "tt_sdrberror": "SD卡读取错误",
    "tt_savetosd": "保存打印数据至SD卡",
    "tt_jogcmderror": "移动指令错误",
    "tt_copyrightzero": "版权限制",
    "tt_printtimelimit": "打印次数限制",
    "tt_commerror": "通讯错误",
    "printerName": "打印机名称",
    "nozzleTemperature": "喷嘴温度",
    "flatTemperature": "平台温度",
    "m_nMaterial": "材料",
    "printerTxt": "打印机名称",
    "m_dNozzleHeight": "喷嘴高度",
    "btn_aboutUs": "关于我们",
    "btn_myCounts": "我的账户",
    "btn_up": "UP",
    "btn_libiray": "资料库",
    "btn_help": "帮助",
    "dialogTitle_add": "添加",
    "dialogAdd_photo": "添加图像",
    "dialogAdd_stl": "添加模型",
    "dialogTitle_layer": "设置",
    "dialogTitle_Z_resolution": "层片厚度",
    "dialogTitle_part": "密闭",
    "dialogTitle_Surface": "密闭层数",
    "dialogTitle_Surface_SupportAngle": "密闭角度",
    "dialogTitle_Support": "支撑",
    "dialogTitle_Dense": "支撑层数",
    "dialogTitle_Support_Angle": "支撑角度",
    "dialogTitle_Support_Area": "支撑面积",
    "dialogTitle_Support_Space": "支撑间隔",
    "dialogTitle_Stable_Support": "稳固支持",
    "dialogTitle_Fill": "填充方式",
    "dialogTitle_fill_shell": "shell",
    "dialogTitle_fill_surface": "surface",
    "dialogTitle_fill_solid": "solid",
    "dialogTitle_fill_Loose": "loose",
    "dialotTitle_fill_Hollow": "Hollow",
    "dialogTitle_fill_BigHole": "Big Hole",
    "ResettoDefault": "设置默认",
    "save": "保存",
    "unsave": "取消",
    "dialogTitle_Maintain": "维护界面",
    "dialogTitle_Maintenance": "维护",
    "dialogTitle_Extrude": "挤出",
    "dialogTitle_Evacuate": "撤回",
    "Stop": "停止",
    "Weight": "重量",
    "dialogTitle_PrinterSetting": "打印设置",
    "dialogTitle_printerName": "打印机",
    "dialogTitle_UnsolidModel": "非实体模型",
    "dialogTitle_NoRaft": "无底座",
    "dialogTitle_heat": "打印完成平台持续加热",
    "dialogTitle_Quality": "质量",
    "option": "选项",
    "reprint": "重复打印",
    "preview": "打印预览",
    "dialogTitle_Calibrate": "平台校准",
    "platMainH3": "平台点位校准",
    "saveImgTo3D_txt": "图像转换中",
    "save3DModeling_txt": "保存中",
    "printBtn": "打印",
    "exit": "退出",
    "ImgTo3D_txt": "转换中",
    "Time_left": "剩余",
    "initialPrinter": "初始化进行中",
    "logIn": "登录",
    "preference": "高级",
    "no_Support": "无支撑",
    "thinWall": "薄壁",
    "others": "其他",
    "autoPlace": "自动摆放",
    "noRecentFile": "没有最近打开",
    "autoUpdateTxt": "有版本更新时请提醒我",
    "apError": "无线网络查找错误",
    "auto": "自动",
    "manual": "手动",
    "platAutoIng": "平台自动调整中,请稍后...",
    "nozzleAutoIng": "喷嘴自动调整中,请稍后...",
    "autoError": "传感器未连接",
    "errorTxt": "错误",
    "connectTxt": "正在连接，请稍后...",
    "successTxt": "成功",
    "setSuccessTxt": "设置成功",
    "setErrorTxt": "设置失败",
    "convert": "转换中",
    "nozzleHeating": "稍等片刻...",
    "math": "计算中",
    "transfer": "传输中",
    "normal": "默认",
    "fine": "较好",
    "fast": "较快",
    "turbo":"极快",
    "timeH": "小时",
    "timeM": "分钟",
    "timeS": "秒",
    "connectSuccessTxt": "连接成功",
    "connectErrorTxt": "连接失败",
    "languageTxt": "语言",
    "PrinterTxt": "打印机",
    "wifiTxt": "无线网络",
    "UpdateTxt": "软件升级",
    "currentTxt": "当前版本",
    "newTxt": "最新版本",
    "axisTxt": "未选择轴方向",
    "yes": "确认",
    "no": "取消",
    "printerInitTips": "是否初始化打印机？",
    "printerStopTips": "是否停止打印？",
    "manualUpdate": "升级",
    "justTxt1": "只能输入",
    "justTxt2": "的数噢",
    "nameError": "打印机名字不能为空~",
    "custom": "自定义",
    "txtObject": "模型",
    "share": "分享到",
    "verTips": "当前版本以为最新",
    "nozzleCurrentHeight": "喷嘴当前高度",
    "nozzleSetHeight": "喷嘴高度",
    "reset": "重置",
    "compensation": "补偿",
    "pausePrintError": "暂停失败",
    "resumePrintError": "恢复打印失败",
    "nozzleTo": "移动",
    "set": "设置",
    "detectNozzle": "自动对高",
    "autoLevel": "自动补偿",
    "saveSetNozzleHeight": "保存喷嘴高度为",
    "intNumberTips": "范围的整数",
    "connectWifiError0x110": "密码错误",
    "connectWifiError0x111": "其他用户已连接此打印机",
    "connectWifiError0x112": "未认证",
    "connectWifiError0x113": "不能连接打印机",
    "connectWifiError0": "没有响应",
    "connectWifiError2": "打印机忙",
    "connectWifiErrorUnknown": "未知错误",
    "sync_tips_resetPrinter":"重启打印机",
    "checkNetwork":"请检查网络，且确保App连接的路由与打印机一致",
    "previewStopTips": "是否停止预览？",
    "ios_Font_WordStyle"  : "文字样式",
    "ios_Font_Keyboard"   : "键  盘 ",
    "ios_Font_Finish"     : "完成",
    "ios_Font_ChangeText" : "修改文字:",
    "ios_Font_Font"       : "文字",
    "ios_Font_PleaseChangWord"  : "点击请输入文字",
    "ios_Alert_Message"  : "模型导入完成是否打开？",
    "ios_Alert_cancel"   : "取消",
    "ios_Alert_OK"       : "确定",
    "ERROR": "发生错误",
    "ERROR: Task cannot be performed during printing": "错误：打印机运行中，不能进行此操作",
    "ERROR: Incorrect material": "错误：打印机材料设置错误",
    "ERROR: Printer status error": "错误：打印机状态错误",
    "ERROR: Slicing error": "错误：分层错误",
    "ERROR: Printer connection error": "错误：打印机连接错误",
    "ERROR: Data transfer failure": "错误：传输打印数据失败",
    "ERROR: Printer is busy,please stop and try again": "错误：系统正忙，请停止后再试",
    "ERROR: Printer material shortage,still continue?": "错误：打印材料不足，是否继续打印？",
    "ERROR: Printer support material shortage,still continue?": "错误：支撑材料不足，是否继续打印？",
    "ERROR: Nozzleheight set error\nCorrect range:": "错误：喷头高度设置错误\n正确范围：",
    "Repeat last print?": "确定重复打印吗？",
    "ERROR: Other error ": "错误：其他错误 ",
    "Language test": "当前语言为中文",
    "Are you sure to stop the print job?": "确定停止打印吗？",
    "Found a new version": "发现新版本",
    ",download it immediately?": "，是否立即更新？",
    "[YES]: Update immediately": "[是]：立即更新",
    "[NO]: Remind me later": "[否]：下次通知我",
    "[CANCEL]: Switch off update reminder": "[取消]：不再提示更新",
    "Note: Download will be run in the background, after the completion of the notice": "注意：程序将在后台下载，完成后进行通知",
    "Update": "升级",
    "No new version": "无新版本",
    "ERROR: The model is opening, please try again later": "错误：正在读取模型，请稍后再试",
    "ERROR: Temperature is too high": "错误：温度过高",
    "ERROR: Sensor not connected": "传感器未连接",
    "ERROR: Calibration failure": "错误：校准失败",
    "ERROR: Printer is busy": "错误：系统正忙",
    "Success，Please reset nozzle height before printing": "调平成功，请重新设置喷头高度后进行打印",
    "ERROR: Printer error": "错误：打印机错误",
    "Print: ": "打印时间：",
    "Material: ": "耗费材料：",
    "g": "克",
    "H": "小时",
    "M": "分钟",
    "S": "秒",
    "ERROR: Templete directory get error": "错误：临时文件路径获取失败",
    "ERROR: Create dir error": "错误：创建目录失败",
    "ERROR: Copy UpdateFile Error_APP": "错误：拷贝升级程序失败_APP",
    "ERROR: Copy UpdateFile Error_DLL": "错误：拷贝升级程序失败_DLL",
    "ERROR: Nozzleheight set error": "错误：喷头高度设置错误",
    "ERROR:Model does not exist": "错误：模型不存在",
    "Activation": "激活",
    "Please activate the printer in time to use the full printer functions": "请及时激活打印机从而使用完整的打印机功能",
    "Activation state error, need to return to the factory": "激活状态错误，请返厂",
    "OK": "确定",
    "CANCEL": "取消",
    "YES": "是",
    "NO": "否",
    "ABORT": "退出",
    "RETRY": "重试",
    "IGNORE": "忽略",
    "Save successful": "保存成功",
    "Save failed": "保存失败",
    "Downloading, please wait": "正在下载，请稍等片刻",
    ",upgrade now?": ",立刻升级？",
    "Level data save error": "调平数据保存错误",
    "ERROR: Printer no response": "错误：打印机无响应",
    "ERROR: Printer password error": "错误：密码错误",
    "ERROR: Printer connected by other clients": "错误：打印机被占用",
    "ERROR: Printer none certification": "错误：打印机未认证",
    "Connection OK": "连接成功",
    "Connection Error": "连接失败",
    "Activation is successful, please restart the printer": "激活成功，请重新启动打印机",
    "Can not Save more than 4 millon facets model": "不能保存超过400万面片的模型",
    "Please close the front door": "请关门前门板",
    "Can not Open more than 1 millon facets temporarily in WIN32 System": "WIN32系统下面暂时不能导入多于100万面片数",
    "Print job stopped at ": "打印任务停在第",
    "th layer, resume the print?": "层，是否恢复打印?",
    "ERROR: Can not resume the broken print job": "错误：恢复打印失败",
    "ERROR: Data transfer failed, try again?": "错误：数据传输失败，是否重试？",
    "OpenGL Version Too Low! Check your Graphic Drivers!": "OpenGL 版本过低，请更新显卡驱动",
    "UnknownName" : "未命名",
    "Please input" : "请输入",
    "link password" : "的密码",
    "Enter password" : "输入密码",
    "Join" : "加入",
    "Joining" : "正在加入",
    "Cannot Join" : "无法加入",
    "user_login":"用户登录",
    "user_name_hint":"邮箱/用户名",
    "password_hint":"密码",
    "sign_in":"登录",
    "sign_up":"注册",
    "ifremember":"记住密码",
    "forget_password":"忘记密码?",
    "username":"用户名",
    "email":"邮箱",
    "ConfirmPassword":"确认密码",
    "username_error":"用户名输入不合法",
    "email_error":"邮箱输入不合法",
    "password_error":"密码输入不合法",
    "confirm_error":"两次密码输入不同",
    "registration_statement":"注册表示您同意",
    "agreement":"《太尔时代用户协议》",
    "login_info":"打印机管理",
    "online_device":"在线设备列表",
    "my_device":"我的设备列表",
    "Device_List":"设备列表",
    "net_error":"网络出问题了，请稍后再试",
    "device_sn":"设备sn号",
    "activate_status":"激活状态",
    "bind_status":"绑定状态",
    "activate":"激活",
    "activated":"已激活",
    "bind":"绑定",
    "binded":"已绑定",
    "unbind":"解除绑定",
    "EmailWrong":"用户名或邮箱错误",
    "UserNameExisted":"用户名已经注册",
    "EmailExisted":"邮箱已存在",
    "unactive":"未激活",
    "PasswordErr":"密码错误",
    "ERROR: Printer SN Error": "错误：打印机序列号有问题",
    "ERROR: Unknow error": "错误：未知错误",
    "ERROR: Invalide activekey": "错误：激活码错误",
    "ERROR: No factory actived": "错误：不是工厂激活状态",
    "ERROR: Active error,wrong key": "错误：激活失败，错误的激活码",
    "ERROR: The server returns the activation code to parse the JSON failed": "错误：服务器返回信息解析JSON失败",
    "ERROR: The server failed to return the activation code": "错误：从服务器返回激活码失败",
    "ERROR: Failed to get the check code from the printer": "错误：从打印机得到校验码失败",
    "ERROR: The current state of activation is not factory activation": "错误：当前的激活状态不是工厂激活",
    "ERROR: Failed to obtain an active state": "错误：获得激活状态失败",
    "No Model saved for reprint": "没有可供重复打印的模型纪录",
    "LoginError:User does not exist":"用户不存在",
    "LoginError:Password Error":"密码错误",
    "LoginError:User not activated":"用户未激活",
    "LoginError:Purchase of goods not registered":"购买商品未注册",
    "LoginError:Registration parameter is not complete":"注册参数不完整",
    "LoginError:Registration parameter check error":"注册参数校验错误",
    "LoginError:User already exists":"用户已存在",
    "LoginError:Data save failed":"数据保存失败",
    "LoginError:Network connection timeout":"网络连接超时",
    "LoginError:Login failed,please try again":"登录失败，请重新尝试",
    "The print model beyond the range":"模型超出打印范围",
    "Password has been successfully sent to the mailbox":"密码已成功发送到邮箱",
    "Sign_out":"退出",
    "ERROR: Validation failure!":"验证失败",
    "Logining...":"正在登录...",
    "Set_InitPrinter":"初始化",
    "Set_StopPreview":"停止预览",
    "Set_StopPrint":"停止打印",
    "Set_Delete":"删除",
    "Set_SelectPrinter":"选择打印机",
    "Set_MaterialName":"名字",
    "Set_MaterialInputName":"请输入名字",
    "Set_MaterialInputTemp":"请输入温度",
    "Set_Custom":"自定义",
    "Set_PlesaeInputMaterialName":"请输入材料名称",
    "Set_PleaseInput1-5Character":"请输入1-5位的字符",
    "Set_NameExist":"名字已存在",
    "Set_Please enter a temperature value":"请输入温度数值",
    "Set_The temperature is not legitimate, please enter 0-300 numbers":"温度不合法，请输入0-300的数字",
    "Set_The temperature is not legitimate, please enter 0-100 numbers":"温度不合法，请输入0-100的数字",
    "Set_incomplete parameters":"参数不完整",
    "Set_Customize the amount of material can not be more than 4":"自定义材料数量不能超过4个",
    "Can not use special characters":"不能使用特殊字符",
    "Pause Printing":"暂停打印",
    "Resume printing":"恢复打印",
    "Quality Model":"精品",
    "Private Model":"私有",
    "Collected Model":"收藏",
    "Published model":"发布",
    "Purchased Model":"购买",
    "Setting":"设置",
    "My Model":"我的模型",
    "My 3D Printer":"我的打印机",
    "View All Printers":"查看所有打印机",
    "User Points":"用户积分",
    "Points":"积分",
    "Sign out":"退出",
    "Activated":"已激活",
    "Bind":"绑定",
    "Activate":"激活",
    "Unbind":"解除绑定",
    "Unbind Successfully":"解绑成功",
    "Failed to Unbind":"解绑失败",
    "Binding Successfully":"绑定成功",
    "Activation Succeeded":"激活成功",
    "Serial Number":"设备号",
    "Activation Status":"激活状态",
    "Binding Status":"绑定状态",
    "User Login":"用户登录",
    "Sign In":"登录",
    "Sign Up":"注册",
    "Remember Me":"记住我",
    "Login Failed":"登录失败",
    "Username/Email":"用户名/邮箱",
    "User does not Existed":"账户不存在",
    "Please enter your username and password":"请输入用户名和密码",
    "Please enter user name":"请输入用户名",
    "Please enter your password":"请输入密码",
    "Login Timeout":"登录超时",
    "Network Problems and Please Try Later":"网络出问题了，请稍后再试",
    "Password is Incorrect":"密码错误",
    "User Account has not been Activated":"账户未激活",
    "Forgot Password?":"忘记密码？",
    "Username":"用户名",
    "Email":"邮箱",
    "Password":"密码",
    "Confirm Password":"确认密码",
    "3-20 Characters Starting with a Letter":"3-20位字符，以字母开头",
    "Enter an Email Address":"请输入你的邮箱",
    "6-32 Characters":"6-32位字符",
    "Input Password Again":"再次输入密码",
    "Registration means you agree with":"注册即表示您同意",
    "Tiertime User Agreement":"太尔时代用户协议",
    "Username has been used":"用户名已存在",
    "Invalid Username":"用户名格式错误",
    "Email account has been used":"邮箱已存在",
    "Invalid Email Address":"邮箱格式错误",
    "Invalid Password":"密码格式错误",
    "Passwords Do Not Match":"密码不匹配",
    "Parameters Error":"参数错误",
    "Congratulations":"恭喜",
    "Registration is successful. An activation code has been sent to your email account.":"注册成功，激活码已发送到您的邮箱",
    "Retrieve Password":"找回密码",
    "Email Adress does not exist or send a message to failure":"邮箱不存在或邮件发送失败",
    "An email to reset your password has been sent to your email address":"重置密码邮件发送成功",
    "Category":"分类",
    "Price":"价格",
    "All":"全部",
    "Charge":"收费",
    "Free":"免费",
    "Please sign in your account":"请登录您的账户",
    "Description":"模型描述",
    "Purchase":"购买",
    "Purchased":"已购买",
    "Unpublish":"取消发布",
    "Publish Model":"发布模型",
    "Model Name":"模型名称",
    "Model Size":"模型大小",
    "Print Times":"打印次数",
    "Model Price":"模型积分",
    "Collection":"收藏",
    "Collected":"已收藏",
    "Download All":"全部下载",
    "Model Infomation":"模型详情",
    "Package":"模型包",
    "Plesae enter the model name":"请输入模型名称",
    "Model Price(points)":"模型价格（积分）",
    "Unlimited":"无限制",
    "Publish":"发布",
    "Pull down to refresh":"下拉可以刷新",
    "Release to refresh immediately":"松开立即刷新",
    "Refreshing datas…":"正在刷新…",
    "Pull up can load more data":"上拉可以加载更多数据",
    "Release to load more data immediately":"松开立即加载更多数据",
    "Loading more datas…":"正在加载数据…",
    "Sure to buy?":"确定购买吗？",
    "Unpublish successful":"取消发布成功",
    "Published successfully":"发布成功",
    "Your points is not enough!":"您的积分不足!",
    "Purchase failed. Please try again":"购买失败，请重试",
    "Plesae enter the model price":"请输入模型价格",
    "No Datas":"没有数据",
    "Please enter a price for pure numbers":"请输入纯数字的价格",
    "Prepare...":"准备...",
    "Being slicing, can not import model":"正在分层，无法导入模型",
    "No material detected, please replace it":"未检测到材料，请更换",
    "Auditing":"审核中",
    "Privacy Policy":"隐私声明",
    "privacyText":"请查看 Tiertime 的隐私声明以了解有关如何使用发送到 Tiertime 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
    "View details":"查看详情",
    "Purchase success":"购买成功",
    "Model purchase choices":"模型购买选择",
    "Customize":"自定义",
    "Purchase quantity":"购买数量",
    "Single-pass printing":"单次打印积分",
    "Unlimited printing":"无限制打印积分"
		},
     "image": { }
}
